services:
    app:
        build:
            context: ./.docker/php
            dockerfile: Dockerfile
            args:
                NODE_VERSION: 20
                VITE_APP_PORT: '${VITE_APP_PORT:-5173}'
        ports:
            - '${VITE_APP_PORT:-5173}:${VITE_APP_PORT:-5173}'
        volumes:
            - '.:/var/www'
        environment:
            VITE_APP_HOST: '${VITE_APP_HOST:-localhost}'
            VITE_APP_PORT: '${VITE_APP_PORT:-5173}'
        depends_on:
            - mysql
    mysql:
        build:
            context: ./.docker/mysql
            dockerfile: Dockerfile
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
        volumes:
            - 'db-store:/var/lib/mysql'
    nginx:
        image: nginx:1.24-alpine
        ports:
            - '${NGINX_PORT:-80}:80'
        volumes:
            - '.:/var/www'
            - './.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf'
        depends_on:
            - app
volumes:
    db-store:
